from __future__ import annotations

# Decision engine reason codes.
REASON_LOW_DELTA = "LOW_DELTA"
REASON_UNSUPPORTED_SIGNAL = "UNSUPPORTED_SIGNAL"
REASON_BIAS_CONFLICT = "BIAS_CONFLICT"
REASON_NO_ROOM = "NO_ROOM"
REASON_EXTENSION_TOO_LARGE = "EXTENSION_TOO_LARGE"
REASON_CHASE_OK = "CHASE_OK"
REASON_HIGH_VOL_DOWNGRADE = "HIGH_VOL_DOWNGRADE"
REASON_STATE_GATE = "STATE_GATE"

# State gate reason codes.
REASON_GATE_PASSED = "STATE_GATE_PASSED"
REASON_COOLDOWN_ACTIVE = "COOLDOWN_ACTIVE"
REASON_SESSION_CLOSED = "SESSION_CLOSED"
REASON_DAILY_LOCKED = "DAILY_LOCKED"
REASON_LOSS_STREAK_BLOCKED = "LOSS_STREAK_BLOCKED"
REASON_DUPLICATE_SIGNAL = "DUPLICATE_IGNORED"

# Risk engine reason codes.
REASON_RISK_BASELINE = "RISK_BASELINE"
REASON_RISK_DAILY_LOSS_GUARD = "RISK_DAILY_LOSS_GUARD"
REASON_RISK_HIGH_VOL_TIGHTEN = "RISK_HIGH_VOL_TIGHTEN"

