$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$envPath = Join-Path $repoRoot ".env"

Write-Host "Setup .env for yui-quant-lab" -ForegroundColor Cyan
Write-Host "Press Enter to keep an existing value." -ForegroundColor DarkGray

$existing = @{}
if (Test-Path $envPath) {
  Get-Content $envPath | ForEach-Object {
    if ($_ -match "^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$") {
      $existing[$matches[1]] = $matches[2]
    }
  }
}

function Read-OrKeep {
  param(
    [string]$Key,
    [string]$Prompt,
    [bool]$AsSecure = $false
  )
  $current = $existing[$Key]
  $hint = if ([string]::IsNullOrWhiteSpace($current)) { "not set" } else { "already set" }
  if ($AsSecure) {
    $secure = Read-Host "$Prompt ($hint)" -AsSecureString
    $plain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
      [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    )
    if ([string]::IsNullOrWhiteSpace($plain)) { return $current }
    return $plain.Trim()
  }
  $value = Read-Host "$Prompt ($hint)"
  if ([string]::IsNullOrWhiteSpace($value)) { return $current }
  return $value.Trim()
}

$enableNotify = Read-OrKeep -Key "ENABLE_TELEGRAM_NOTIFY" -Prompt "ENABLE_TELEGRAM_NOTIFY [true/false]"
if ([string]::IsNullOrWhiteSpace($enableNotify)) {
  $enableNotify = "true"
}

$botToken = Read-OrKeep -Key "TELEGRAM_BOT_TOKEN" -Prompt "TELEGRAM_BOT_TOKEN" -AsSecure $true
$chatId = Read-OrKeep -Key "TELEGRAM_CHAT_ID" -Prompt "TELEGRAM_CHAT_ID (numeric)"
$tvSecret = Read-OrKeep -Key "TV_WEBHOOK_SECRET" -Prompt "TV_WEBHOOK_SECRET" -AsSecure $true

if ([string]::IsNullOrWhiteSpace($botToken) -or [string]::IsNullOrWhiteSpace($chatId) -or [string]::IsNullOrWhiteSpace($tvSecret)) {
  throw "TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID, and TV_WEBHOOK_SECRET are required."
}

if ($chatId -notmatch "^-?\d+$") {
  throw "TELEGRAM_CHAT_ID must be numeric (e.g. 123456789 or -1001234567890)."
}

$lines = @(
  "# Auto-generated by scripts/setup_env.ps1",
  "ENABLE_TELEGRAM_NOTIFY=$enableNotify",
  "TELEGRAM_BOT_TOKEN=$botToken",
  "TELEGRAM_CHAT_ID=$chatId",
  "TV_WEBHOOK_SECRET=$tvSecret"
)

Set-Content -Path $envPath -Value $lines -Encoding utf8
Write-Host "Saved $envPath" -ForegroundColor Green
Write-Host "Now restart app: python app.py" -ForegroundColor Yellow
